### ISSUE TITLE
Error on TitTacToe

### ISSUE THREAD

**Issue by Malachiel87** [rodel77/MiniBoardGames#11]
https://hastebin.com/feniwisawu.md

**Comment by rodel77** [comment]
The error is not explicit, added more info in the report for next update, report it again on the next time you have it!

**Comment by Malachiel87** [comment]
Here there is the error with 2.9.5
https://hastebin.com/ofuvoyafem.md

**Comment by rodel77** [comment]
That error explain everything, fixed for next update

Thanks for your report
