### ISSUE TITLE
the command /mbg reload is useless

### ISSUE THREAD

**Issue by Malachiel87** [rodel77/MiniBoardGames#14]
I noticed the command /mbg reload it just regenerate the config file to old config without applying the new edit on it :(

**Comment by rodel77** [comment]
It works perfect for me, what config node are you trying to change?
And are you sure the config file is called `config.yml`, you are saving it good, etc?

**Comment by Malachiel87** [comment]
it work, maybe was caused by the old versions (json ecc)
