### ISSUE TITLE
High timings on Minesweeper and a few on Hearthstone

### ISSUE THREAD

**Issue by Malachiel87** [rodel77/MiniBoardGames#15]
I just taked the timings for some hours and these are the result, i got some low lag on my hub but i think MBG is the cause, exact the minesweeper game and hearthstone game
https://timings.spigotmc.org/?url=dibunahojo

**Comment by rodel77** [comment]
Hearthstone:
That timer is the timer for sounds, only is executed 4 times (4 sounds) i will try to optimize it, use delay instead timer

Minesweeper:
The only tasks minesweeper has is delay for end the game, and other to broadcast the winner, i optimize some things but i dont think this remove the problem (If you have too much players playing it is normal, minesweeper has a slow generate code, but is the only way i found to make it good and real)
