### ISSUE TITLE
Menu opens then closes uppon playing ANY game.

### ISSUE THREAD

**Issue by BlueYoshi68** [rodel77/MiniBoardGames#16]
read the title.

**Comment by rodel77** [comment]
Any console error?
And can you tell me what MC version are you using?

**Comment by rodel77** [comment]
Hello, you can give me the info i ask above?

**Comment by rodel77** [comment]
Can you please confirm me if this error has been fixed, otherwise please send me more information, Spigot Verison, MBG Version, any console error log

**Comment by rodel77** [comment]
Closed for lack of info
