### ISSUE TITLE
Busy player advise, disable it on normal chat

### ISSUE THREAD

**Issue by Malachiel87** [rodel77/MiniBoardGames#17]
I am using chatcontrol as chat manager, and i noticed when i chat normal (no private message) and i am close to playing player it keep to show the  message about user that it can be busy in the game, that message should appaer only if i try to whisper/msg him, and not when i chat in pubblic

**Comment by Malachiel87** [comment]
I noticed the message trigger when you write the initial or letter that start with their name

**Comment by rodel77** [comment]
Added config option
