### ISSUE TITLE
Uno Bug

### ISSUE THREAD

**Issue by ReLexioN** [rodel77/MiniBoardGames#29]
hey im using your plugin but i have a problem i tried with latest version but didn't work problem is the card number doesn't decrease or increase in the UNO (amount in player's head) can you fix that problem?

**Comment by rodel77** [comment]
Any error in console if is not error then can you send me a gif of that, its working good for me?

**Comment by rodel77** [comment]
Closed for lack of info, please if you open a issue stay tunned and give the info i need to fix it!!
