### ISSUE TITLE
Boardgame error ThisIsXmas version server 1.8 spigot

### ISSUE THREAD

**Issue by NakungII** [rodel77/MiniBoardGames#37]
In my server 1.8 spigot
when I play ThisIsXmas
nothing happen but hologram still on my head
and not disappear ever

![1](https://user-images.githubusercontent.com/15090482/38070425-12fd1b80-3346-11e8-9cd7-ad18eae9ee9a.jpg)

**Comment by rodel77** [comment]
Fixed in MBG [3.3.2](https://www.spigotmc.org/resources/30066/update?update=218369)

**Comment by NakungII** [comment]
Thx <3
