### ISSUE TITLE
Error Close minigame Apples to apples 

### ISSUE THREAD

**Issue by NakungII** [rodel77/MiniBoardGames#38]
Spigot 1.8 
when one player press esc to cancel
they can't join other game
it appears like this
this happen in Apples to apples
and hologram still appear

![2](https://user-images.githubusercontent.com/15090482/38076637-66c35120-3360-11e8-821e-7adc8684e77c.jpg)
![3](https://user-images.githubusercontent.com/15090482/38076638-66f91274-3360-11e8-8bb2-9f0bd84e664f.jpg)

**Comment by rodel77** [comment]
There are more error logs? I cannot see where my plugin is causing it

**Comment by NakungII** [comment]
It works fine now , Thx
