### ISSUE TITLE
bug new  version v.3.3.3

### ISSUE THREAD

**Issue by NakungII** [rodel77/MiniBoardGames#42]
![02](https://user-images.githubusercontent.com/15090482/38597315-11937da8-3d81-11e8-901e-ee164b92f2ff.jpg)
![01](https://user-images.githubusercontent.com/15090482/38597316-11c53c94-3d81-11e8-975a-15b28d0bcea9.jpg)

**Comment by rodel77** [comment]
Fixed in 3.3.4: https://www.spigotmc.org/resources/30066/update?update=220433
