### ISSUE TITLE
v 3.3.4 not working

### ISSUE THREAD

**Issue by NakungII** [rodel77/MiniBoardGames#43]
![1](https://user-images.githubusercontent.com/15090482/38597713-7fa4b044-3d83-11e8-8d27-805db67a2fa6.jpg)

have Holograms and Vault last version

**Comment by rodel77** [comment]
Damned idea for any reason didn't compile the plugin.yml file, try the new version: https://www.spigotmc.org/resources/30066/update?update=220435
