### ISSUE TITLE
Text Formating issues

### ISSUE THREAD

**Issue by LadyHaley** [rodel77/MiniBoardGames#47]
![image](https://user-images.githubusercontent.com/3754909/52358886-e3f84f00-2a8c-11e9-9db2-1c9b4abff882.png)
![2019-02-07_03-55-27](https://user-images.githubusercontent.com/3754909/52358907-f07ca780-2a8c-11e9-9ce3-7e22bdbed79e.png)
![2019-02-07_03-58-06](https://user-images.githubusercontent.com/3754909/52358918-f3779800-2a8c-11e9-88af-ac24956c205f.png)

I noticed these issues with the text, I dont thing I saw them with the previous version but I could be wrong

**Comment by rodel77** [comment]
I am very busy now and nearly impossible to update the plugins, but I will maintain this issue open to fix it when I have some time

**Comment by LadyHaley** [comment]
https://pastebin.com/eHVXSJsd

Is the log above related to that text bug???
